# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0e979e9ff66511772b53138773b2386aa713557e319824085a8806ce6d74c60a0fb0b025b828b05ebc78cb3b5ae4968b5ed88d1a85d38bb4153a44aa000c33

test:
  secret_key_base: 4e801674e4714cca9cbe0b52152ef77c68fd2b705e7c6d598e18f70f9bfe3829a056f8af95926c6c2ce1d65e32aa96effded99ae890aa9714147c984a72a2c3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
