# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0c66908aeeae1399b814e88c75ed6690792e195524bb53ebc09768025894c0f7f148599e05408e4473de7001f6ef985f7c8a82ec062a077b43fe679cb6bc9bd

test:
  secret_key_base: a640b8c4f80c0df27cc87cd2bf6062f888e48c3186e58202716db24ccec3fb75fd78ac1948a053a0536eb2c0fa708ce174a66731d70873b18dbf76ee294ac6a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
